

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/propagation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl.auto: create
        #        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
#logging:
#  level:
#    org:
#      springframework:
#        transaction:
#          interceptor: trace
