
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: 1q2w3e4r5t
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl.auto: create
#        #          ddl-auto: create
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl.auto: create-drop
#        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG